spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres}
    username: ${DB_USER:postgres.clobleulphasflvdrzxk}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:smartcarcosts.app@gmail.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
    base-url: ${APP_BASE_URL:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET:SmartCarCosts_Super_Secret_Key_For_JWT_Tokenization_2026}