spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres}
    username: ${DB_USER:postgres.clobleulphasflvdrzxk}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:3}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USER:smartcarcosts.app@gmail.com}
    password: mucf bcll lkce gigz

    protocol: smtps
    properties:
      mail:
        smtps:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
    base-url: ${APP_BASE_URL:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET:SmartCarCosts_Super_Secret_Key_For_JWT_Tokenization_2026}

server:
   error:
    whitelabel:
    enabled: false
